language: php

php:
  - 5.4
  - 5.5

matrix:
  include:
    - php: 5.5
      env:
        - COVERALLS=1

before_script:
  - sh -c "if [ '$COVERALLS' = '1' ]; then composer require --dev satooshi/php-coveralls:dev-master; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then composer install --dev --no-interaction --prefer-source; fi"

script:
  - sh -c "if [ '$COVERALLS' != '1' ]; then phpunit -c app --stderr; else phpunit -c app --stderr --coverage-clover build/logs/clover.xml; fi"

after_script:
  - sh -c "if [ '$COVERALLS' = '1' ]; then php bin/coveralls -v; fi"
